// Optional browser integration test: Node.js, Playwright, installed Edge and the project CUDA .venv.
// Run from the repository root: node tests/board_2048_smoke.cjs
const { chromium } = require('playwright');
const {spawn,spawnSync}=require('child_process');
const path=require('path'),fs=require('fs'),assert=require('assert');
const root=process.cwd(),python=path.join(root,'.venv','Scripts','python.exe');
const app=spawn(python,['-u','tqdmboard.py','--no-browser'],{cwd:root,windowsHide:true});
let output='',url,browser;
app.stdout.on('data',b=>output+=b.toString());app.stderr.on('data',b=>output+=b.toString());
const wait=async(fn,seconds=60)=>{const end=Date.now()+seconds*1000;while(!await fn()){if(Date.now()>end)throw Error('Timeout: '+fn+'\n'+output.slice(-2000));await new Promise(r=>setTimeout(r,60));}};
const state=async()=>{const r=await fetch(url+'state');return r.json();};
(async()=>{try{
 await wait(()=>{url=output.match(/tqdmboard: (http:\/\/127\.0\.0\.1:\d+\/)/)?.[1];return url;});
 browser=await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url);await wait(async()=> (await page.locator('#script').inputValue()).endsWith('rl2048_demo.py'));
 assert.strictEqual(await page.locator('iframe').count(),0);
 await page.locator('#advanced-section > summary').click();
 await page.locator('#arguments').fill('--steps 2000 --batch-size 32 --warmup 64 --step-delay 0.003');
 await page.locator('#run').click();
 await wait(async()=>{const t=(await state()).training.data;return t&&t.completed>=100&&Number(t.metrics.updates)>0;});
 assert((await page.locator('#console-output').innerText()).includes('RTX 5060'));
 await wait(async()=> (await page.locator('#training-metrics').innerText()).includes('loss'));
 await page.locator('#training-pause').click();
 await wait(async()=> (await state()).training.data?.control.paused);
 const before=(await state()).training.data.completed;
 const start=Date.now();
 await page.locator('#training-lr-input').fill('0.0002');await page.locator('#training-lr-apply').click();
 await wait(async()=> (await state()).training.data.control.learning_rate===0.0002);
 const lag=Date.now()-start;assert(lag<3000);assert.strictEqual((await state()).training.data.completed,before);
 await page.locator('#training-save').click();
 let manual;await wait(async()=>{manual=(await state()).training.data.control.last_checkpoint;return manual;});
 assert(fs.existsSync(manual));
 const check=spawnSync(python,['-c',`import sys,torch; s=torch.load(sys.argv[1],weights_only=True); assert s['format']=='qtqdm-2048-v1'; assert s['training']['next_step']==int(sys.argv[2]); assert s['optimizer']['param_groups'][0]['lr']==0.0002; assert s['training']['updates']>0; assert s['board'].shape==(4,4); assert len(s['replay']['state_memory'])==min(s['replay_count'],s['replay_capacity']); assert 'q_action.fc.0.weight' in s['agent']; assert 'q_eval.fc.0.weight' in s['agent']; print('RL checkpoint verified')`,manual,String(before)],{cwd:root,windowsHide:true,encoding:'utf8'});
 assert.strictEqual(check.status,0,check.stderr);
 await page.locator('#training-save-step').fill(String(before+10));await page.locator('#training-save-schedule').click();
 await wait(async()=> (await state()).training.data.control.save_at_step===before+10);
 await page.locator('#training-save-cancel').click();await wait(async()=> (await state()).training.data.control.save_at_step===null);
 const scheduled=before+5;
 await page.locator('#training-save-step').fill(String(scheduled));await page.locator('#training-save-schedule').click();
 await wait(async()=> (await state()).training.data.control.save_at_step===scheduled);
 await page.locator('#training-pause').click();
 let scheduledPath;await wait(async()=>{scheduledPath=(await state()).training.data.control.last_checkpoint;return scheduledPath&&scheduledPath!==manual;});
 assert(scheduledPath.includes('step_'+String(scheduled).padStart(6,'0')));assert(fs.existsSync(scheduledPath));
 await page.locator('#training-overview-settings select[name=x]').selectOption('3');
 await page.locator('#training-overview-settings select[name=y]').selectOption('score');
 assert((await page.locator('#training-chart-overview canvas').getAttribute('aria-label')).includes('Update Index'));
 await page.locator('#training-stop').click();await wait(async()=> (await state()).training.data.state==='stopped');
 const firstJob=(await state()).job_id;
 await page.locator('#arguments').fill(`--resume "${scheduledPath}" --steps ${scheduled+150} --step-delay 0.001`);
 await page.locator('#restart-process').click();
 await wait(async()=>{const b=await state();return b.job_id===firstJob+1&&b.training.data?.state==='finished';});
 const final=(await state()).training.data;
 assert.strictEqual(final.completed,scheduled+150);assert.strictEqual(final.control.learning_rate,0.0002);
 assert(Number(final.metrics.updates)>0);assert(Number.isFinite(Number(final.metrics.loss)));
 assert.strictEqual(await page.locator('#training-overview-settings select[name=x]').inputValue(),'2');
 assert.strictEqual(await page.locator('#training-overview-settings select[name=y]').inputValue(),'loss');
 assert((await page.locator('#console-output').innerText()).includes('Resumed at: '+scheduled));
 await page.reload();await wait(async()=> (await page.locator('#training-state').innerText())==='Completed');
 await page.locator('#advanced-section > summary').click();
 await page.screenshot({path:path.join(root,'runs','board-2048-preview.png'),fullPage:true});
 await page.locator('#stop-process').click();await wait(async()=> !(await state()).running);
 assert.strictEqual((await state()).training.data.completed,scheduled+150);
 assert.strictEqual(errors.length,0,errors.join('\n'));
 console.log(JSON.stringify({result:'PASS',gpu:'RTX 5060',control_lag_ms:lag,checkpoint_step:scheduled,final_step:final.completed,optimizer_updates:final.metrics.updates,loss:final.metrics.loss,best_tile:final.metrics.best_tile,features:['Board-owned UI','Pause/Resume','Learning Rate','Save','Schedule/Cancel','Chart Axes','Stop Training','Restart Process with Resume','Reload','Retained Final Data']}));
 await page.locator('#quit').click();await wait(()=>app.exitCode!==null);assert.strictEqual(app.exitCode,0);
}finally{
 if(url&&app.exitCode===null){try{await fetch(url+'shutdown',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});}catch{}try{await wait(()=>app.exitCode!==null,10);}catch{}}
 if(browser)await browser.close();
}})().catch(e=>{console.error(e);process.exitCode=1;});
